name = "Envelope2and3phases"
version = "0.1.0"
license = "license"
author = "Federico E. Benelli"
maintainer = "federico.benelli@mi.unc.edu.ar"
copyright = "Copyright 2022, Federico E. Benelli"

[build]
# link = ["lapack", "openblas"]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
ftools = { git="https://github.com/fedebenelli/ftools" }
stdlib = { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm" }
# minpack = { git="https://github.com/fortran-lang/minpack" }
# toml-f = { git="https://github.com/toml-f/toml-f" }
