name = "Envelope2and3phases"
version = "0.1.0"
license = "license"
author = "Federico E. Benelli"
maintainer = "fedebenelli@outlook.com"
copyright = "Copyright 2022, Federico E. Benelli"

[build]
link = ["lapack", "blas"]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
stdlib = { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm" }

