# Example input file
[system]
model = "SoaveRedlichKwong"
use_parameters = false  # Use EOS parameters instead of critical constants
mixing_rule = "ClassicVdW"
composition = [
    { name = 'nitrogen', z = 0.0049051995114821716, use_parameters = false },
    { name = 'carbon_dioxide',   z = 0.1138106392776343, use_parameters = false },
    { name = 'hidrogen_sulfide', z = 0.03223416821831141, use_parameters = false   },
    { name = 'methane', z = 0.27386029190942396, use_parameters = false   },
    { name = 'ethane', z = 0.09418984123170561, use_parameters = false   },
    { name = 'propane', z = 0.06706108474983483, use_parameters = false },
    { name = 'isobutane', z = 0.008108595110817466, use_parameters = false },
    { name = 'butane', z = 0.03173363765591527, use_parameters = false },
    { name = 'isopentane', z = 0.012212945722465816, use_parameters = false },
    { name = 'pentane', z = 0.019821010270887143, use_parameters = false },
    { name = 'hexane', z = 0.024926422007327767, use_parameters = false },
    { name = 'c7-25', z = 0.25304823112499253, use_parameters = false },
    { name = 'c26-49', z = 0.05529861653352554, use_parameters = false },
    { name = 'c50-64-PN', z = 0.005455783130117926, use_parameters = false },
    { name = 'c65-80-PN', z = 0.0018319418583698723, use_parameters = false },
    { name = 'c50-80-A', z = 0.0015015916871884, use_parameters = false },
]

[c7-25.pure]
name = "C7-C25"
Tc = 666.2500
Pc = 20.3900
Vc = 0.756000
w = 0.90559

[c7-25.SoaveRedlichKwong]
a = 64.3343
b = 0.235383
k = 1.569925

[c26-49.pure]
name = "C26-C49"
Tc = 893.9500
Pc = 14.1900
Vc = 1.262000
w = 1.74600

[c26-49.SoaveRedlichKwong]
a = 166.4292
b = 0.453822
k = 2.187675

[c50-64-PN.pure]
name = "C50-C64-PN"
Tc = 956.9500
Pc = 13.7200
Vc = 1.313000
w = 1.93307

[c50-64-PN.SoaveRedlichKwong]
a = 197.2467
b = 0.502447
k = 2.244967

[c65-80-PN.pure]
name = "C65-C80-PN"
Tc = 1118.4500
Pc = 14.1000
Vc = 0.876000
w = 2.19842

[c65-80-PN.SoaveRedlichKwong]
a = 262.1799
b = 0.571416
k = 1.724533

[c50-80-A.pure]
name = "C50-C80-A"
Tc = 1286.7500
Pc = 18.1100
Vc = 1.274000
w = 1.96920

[c50-80-A.SoaveRedlichKwong]
a = 270.1813
b = 0.511836
k = 2.201238



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "carbon_dioxide"
kij = -0.032
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "hidrogen_sulfide"
kij = 0.17
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "methane"
kij = 0.028
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "ethane"
kij = 0.041
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "propane"
kij = 0.076
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "isobutane"
kij = 0.094
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "butane"
kij = 0.07
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "isopentane"
kij = 0.087
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "pentane"
kij = 0.088
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "hexane"
kij = 0.08
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "c7-25"
kij = 0.08
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "c26-49"
kij = 0.08
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "c50-64-PN"
kij = 0.08
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "c65-80-PN"
kij = 0.08
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "nitrogen"
name_2 = "c50-80-A"
kij = 0.08
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "hidrogen_sulfide"
kij = 0.099
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "methane"
kij = 0.12
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "ethane"
kij = 0.12
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "propane"
kij = 0.12
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "isobutane"
kij = 0.12
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "butane"
kij = 0.12
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "isopentane"
kij = 0.12
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "pentane"
kij = 0.12
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "hexane"
kij = 0.12
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "c7-25"
kij = 0.1
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "c26-49"
kij = 0.1
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "c50-64-PN"
kij = 0.1
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "c65-80-PN"
kij = 0.1
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "carbon_dioxide"
name_2 = "c50-80-A"
kij = 0.1
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "methane"
kij = 0.08
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "ethane"
kij = 0.085
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "propane"
kij = 0.089
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "isobutane"
kij = 0.051
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "butane"
kij = 0.06
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "isopentane"
kij = 0.06
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "pentane"
kij = 0.069
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "hexane"
kij = 0.05
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "c7-25"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "c26-49"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "c50-64-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "c65-80-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hidrogen_sulfide"
name_2 = "c50-80-A"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "methane"
name_2 = "ethane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "methane"
name_2 = "propane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "methane"
name_2 = "isobutane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "methane"
name_2 = "butane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "methane"
name_2 = "isopentane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "methane"
name_2 = "pentane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "methane"
name_2 = "hexane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "methane"
name_2 = "c7-25"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "methane"
name_2 = "c26-49"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "methane"
name_2 = "c50-64-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "methane"
name_2 = "c65-80-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "methane"
name_2 = "c50-80-A"
kij = 0.017
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "ethane"
name_2 = "propane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "ethane"
name_2 = "isobutane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "ethane"
name_2 = "butane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "ethane"
name_2 = "isopentane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "ethane"
name_2 = "pentane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "ethane"
name_2 = "hexane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "ethane"
name_2 = "c7-25"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "ethane"
name_2 = "c26-49"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "ethane"
name_2 = "c50-64-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "ethane"
name_2 = "c65-80-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "ethane"
name_2 = "c50-80-A"
kij = 0.017
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "propane"
name_2 = "isobutane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "propane"
name_2 = "butane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "propane"
name_2 = "isopentane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "propane"
name_2 = "pentane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "propane"
name_2 = "hexane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "propane"
name_2 = "c7-25"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "propane"
name_2 = "c26-49"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "propane"
name_2 = "c50-64-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "propane"
name_2 = "c65-80-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "propane"
name_2 = "c50-80-A"
kij = 0.017
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isobutane"
name_2 = "butane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isobutane"
name_2 = "isopentane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isobutane"
name_2 = "pentane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isobutane"
name_2 = "hexane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isobutane"
name_2 = "c7-25"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isobutane"
name_2 = "c26-49"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isobutane"
name_2 = "c50-64-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isobutane"
name_2 = "c65-80-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isobutane"
name_2 = "c50-80-A"
kij = 0.017
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "butane"
name_2 = "isopentane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "butane"
name_2 = "pentane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "butane"
name_2 = "hexane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "butane"
name_2 = "c7-25"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "butane"
name_2 = "c26-49"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "butane"
name_2 = "c50-64-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "butane"
name_2 = "c65-80-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "butane"
name_2 = "c50-80-A"
kij = 0.017
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isopentane"
name_2 = "pentane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isopentane"
name_2 = "hexane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isopentane"
name_2 = "c7-25"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isopentane"
name_2 = "c26-49"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isopentane"
name_2 = "c50-64-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isopentane"
name_2 = "c65-80-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "isopentane"
name_2 = "c50-80-A"
kij = 0.017
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "pentane"
name_2 = "hexane"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "pentane"
name_2 = "c7-25"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "pentane"
name_2 = "c26-49"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "pentane"
name_2 = "c50-64-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "pentane"
name_2 = "c65-80-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "pentane"
name_2 = "c50-80-A"
kij = 0.017
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hexane"
name_2 = "c7-25"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hexane"
name_2 = "c26-49"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hexane"
name_2 = "c50-64-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hexane"
name_2 = "c65-80-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "hexane"
name_2 = "c50-80-A"
kij = 0.017
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "c7-25"
name_2 = "c26-49"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "c7-25"
name_2 = "c50-64-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "c7-25"
name_2 = "c65-80-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "c7-25"
name_2 = "c50-80-A"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "c26-49"
name_2 = "c50-64-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "c26-49"
name_2 = "c65-80-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "c26-49"
name_2 = "c50-80-A"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "c50-64-PN"
name_2 = "c65-80-PN"
kij = 0.0
lij = 0



[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "c50-64-PN"
name_2 = "c50-80-A"
kij = 0.0
lij = 0


[[ClassicVdW.SoaveRedlichKwong]]
name_1 = "c65-80-PN"
name_2 = "c50-80-A"
kij = 0.0
lij = 0
